# Site settings
title: Dennis Alp
description: Dennis Alp's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://dennisalp.com"

# User settings
username: Dennis Alp
user_description: Hard-working, versatile, goal-oriented high achiever 🎯
user_title: '"AI" Trader 🤖 | Data Scientist 📊 | Astrophysics PhD 🌌'
email: website@dennisalp.com
#twitter_username: 
github_username: dennisalp
#gplus_username:

# Google-analytics
google-analytics:
  id: G-8ZVFJEGPPE

exclude: ['package.json', 'src' , 'node_modules']
