# Site settings
title: Dennis Alp
description: Dennis Alp's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://dennisalp.com"

# User settings
username: Dennis Alp
user_description: I'm a data scientist at <b>Handelsbanken</b> in Stockholm, Sweden. I'm originally from Stockholm and have a degree in engineering physics and a PhD in astrophysics, both from <b>KTH Royal Institute of Technology</b>.
user_title: Data Scientist
email: me@dennisalp.com
#twitter_username: 
github_username: dennisalp
#gplus_username:

# Google-analytics
google-analytics:
  id: G-8ZVFJEGPPE

exclude: ['package.json', 'src' , 'node_modules']
